In [2]:
import numpy as np

In [6]:
# np.copy() Does what it says on the tin: copies the data in an array.
num_arr=np.array([0,5,10,100,1000,10000])
slice=np.copy(num_arr[1:3])
slice[0] = 1


[    0     5    10   100  1000 10000]


In [9]:
# np.reshape() - Changes an array's shape to the value you specify.
x = np.array([([1,2,3,4]),
    [5,6,7,8],
    [9,10,11,12]])

np.reshape(x, (4,3))

# Array reshaped from 3x4 into a 4x3 matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
# np.resize() - changes the actual shape of the array instead of performing a temporary transformation like reshape does.

x_resize = np.resize(x, (3,4))
x = np.array([[0,12,24],
       [36,48,60],
        [72,84,96],
        [0,12,24]])
print(x_resize)

# Resized from 4,3 back to 3,4

[[ 0 12 24 36]
 [48 60 72 84]
 [96  0 12 24]]


In [18]:
# np.ravel() - flattens an array into a single dimension.
# np.flatten() also works, but also returns a copy of the array instead of a view.

x = np.array([[1,2,3],
              [4,5,6]])

np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [20]:
# np.flip() - reverses the order of items in an array while keeping the shape.
# specify 0 for rows and 1 for columns in np.flip() e.g. np.flip(x,0)

x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

np.flip(x)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [21]:
# np.transpose() shifts data to opposite dimensions in an array. E.g column values shifted to rows.

x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
np.transpose(x)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
# np.concatenate = combines multiple arrays together to produce a tuple.

x = np.array([1,2,3])
y = np.array([4,5,6])

np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [23]:
# np.append() - same function as concatenate, but takes two arguments instead of a single tuple.

x = np.array([[1,2,3],
              [4,5,6]])
y = np.array([[7,8,9],
              [10,11,12]])

np.append(x,y)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# Stacking functions:
# np.vstack() = combines arrays along rows.
# np.hstack() = combines arrays along columns.
# np.dstack() = combines arrays along third axis. 

In [24]:
# np.stack() = combines arrays along a new axis. Add axis=1 to combine by column.

x = np.array([1,2,3])
y= np.array([4,5,6])
np.stack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# np.split(tuple, how many arrays) = splits a tuple into multiple arrays.

x = np.array([1,2,3,4,5,6])
np.split(x, 2)

[array([1, 2, 3]), array([4, 5, 6])]

In [ ]:
# np.vsplit() = splits arrays along rows.
# np.hsplit() = splits arrays along columns.
# np.dsplit() = splits arrays along third axis.

In [26]:
# np.array_split() performs a split even when a split is not possible with np.split().

x = np.array([1,2,3,4,5,6])
np.array_split(x,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [27]:
# np.sort() = sorts items in an array in ascending order.
x = np.array([4,3,1,5,2])
np.sort(x)

# If you sort a multi-dimensional array, it will be sorted by the last axis. E.g. a two-dimensional array will be sorted by column. To sort by rows, add axis=0 in the ().

array([1, 2, 3, 4, 5])

In [29]:
# np.argsort = returns the indices of each cell in the array in ascending order.

np.array([4,3,5,1,2])
np.argsort(x)

# Index 3 holds the smallest non-zero value so it is assigned the value of '1' in the output.

array([2, 4, 1, 0, 3], dtype=int64)

In [30]:
# np.partition() - partitions low and high values according to specified number of values. 

x=np.array([8,9,3,4,1,6,5])
np.partition(x, 3)

# The three lowest numbers are sent to the beginning of the array and the rest are placed to the right.

array([1, 4, 3, 5, 9, 6, 8])

In [ ]:
# np.argmax() = returns the indices of maximum value in an array. np.argmin() is for minimum.
# np.nonzero() = returns the indices of all non-zero items in the form of a tuple.
# np.argwhere() = returns the indices of all non-zero items in an array.

In [31]:
# np.insert() = specifies where you want to add new data to an existing array.
x1 = np.array([1,2,3,7,8,9])
x2 = np.array([4,5,6])

np.insert(x1, 3, x2)

# This inserts x2 array into x1 before the third index.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# np.delete() = removes data from an array instead of adding it.
x = np.array([1,2,3,9,4,5,6])
np.delete(x,3)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# np.exp() = returns the exponential function of each array value.
# np.expm10() = returns exponential minus 1.
# np.exp2() = returns 2 raised to the power of each array value.
# np.log() = returns natural logarithm of each array value.
# np.log10() = returns base-10 logarithm of each array value.
# np.log2() = returns base-2 logarithm of each array value.
# np.log1p() = returns natural logarithm plus 1 of each array value.

# np.sin() = returns the sine of each value in an array.
# np.cos() = returns the cos of each value in an array.
# np.tan() = returns the tan of each value in an array.
# np.hypot(x1,x2) = returns the hypotenus of a right triangle.
# np.absolute() = returns the absolute number of each value in an array.
# np.square() = returns the square of each number in an array.
# np.sqrt() = returns the square root of each number in an array.
# np.around() = returns rounded numbers of each value in an array.


In [35]:
arr = ([[2,4],
        [6,8],
        [10,12],
        [14,16]])
x=np.transpose(arr)
print(x)

[[ 2  6 10 14]
 [ 4  8 12 16]]


In [38]:
arr = np.array([0, 2, 3, 0, 1, 6, 0, 2])
var = 6
print(arr != var)

[ True  True  True  True  True False  True  True]


In [39]:
import pandas as pd
data = [['Hockey', 45, 55, 50], ['Badminton', 60, 40, 50], ['Volleyball', 55, 70, 45], ['Basketball', 65, 35, 70]]
df = pd.DataFrame(data, columns = ['Sport', 'Team A', 'Team B', 'Team C'])
print(df)
print('\n')
x = df[['Team A', 'Team B', 'Team C']].gt(55)
print(x)

        Sport  Team A  Team B  Team C
0      Hockey      45      55      50
1   Badminton      60      40      50
2  Volleyball      55      70      45
3  Basketball      65      35      70


   Team A  Team B  Team C
0   False   False   False
1    True   False   False
2   False    True   False
3    True   False    True


In [ ]:
# df.transpose() - flips the rows and columns of a dataframe, allowing you to alter its orientation.
# df.sort_values() - Does what it says on the tin.
# df.sort_index() - Sorts row or column labels,

# Additional Parameters Some additional parameters include: ascending—Specify whether the sort should be ascending (True) or descending (False). 
# # inplace—Specify whether or not to change the DataFrame object in place after the sort. 
# kind—Specify the sorting algorithm to use. 
# na_position—Specify whether NaN values should be placed first or last.